version: '3.8'

services:

  postgres:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: ./server/
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  gateway:
    build: ./gateway/
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

